# -*- coding: utf-8 -*-
"""ETO NA TLGA GUYS FINAL NA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJByxP2BQyGAQTFvGxPMg8vTuIto2FuN

# TIBOK — Combined MIT-BIH + INCART, RR-Interval-Fused 1D-CNN (Colab-ready)

Trains on the **combined MIT-BIH + St. Petersburg INCART Arrhythmia Databases**, patient-level
70% train / 15% val / 15% test split — exactly the protocol already described in Section C
("Model Architecture Training") and Section XI ("Data Collection") of the pre-oral document.
INCART's 75 twelve-lead recordings are resampled from their native 257 Hz to the shared 360 Hz
working rate, with lead II pulled as the MLII-equivalent channel per the document's stated plan.

Architecturally this is identical to `TIBOK_RR_CNN.ipynb` (the MIT-BIH-only ablation kept
alongside this notebook for comparison): each ECG window is paired with 4 RR-interval features
(pre-RR, post-RR, causal local-average RR, prematurity ratio), fused into the classifier head
next to the CNN's pooled output. The only change here is the training population — MIT-BIH
alone left the network under-exposed to how "normal" and "abnormal" morphology look across
different hospitals/equipment, which capped precision on held-out patients. Pooling in INCART's
more varied population is the standard fix for that inter-patient generalization gap (Qi et al.,
2023, cited in the RRL, report the same effect from pooling these two databases).

**Architecture**: ECG window (1250×1) → 3×Conv1D(16/32/64, k7, BN+ReLU+SpatialDropout) →
GlobalAveragePooling1D(64) ⊕ RR features (4) → Dense(16) → Concat(80) → Dense(32) → Dropout →
Output(1, sigmoid).
"""

!pip install -q wfdb

from google.colab import drive
drive.mount('/content/drive')  # required below — MIT-BIH/INCART are cached here, not streamed

import os, json, time
import numpy as np
import pandas as pd
import wfdb
import tensorflow as tf
from tensorflow.keras import layers, models, Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import (
    average_precision_score, roc_auc_score, precision_recall_curve,
    confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
)
from sklearn.utils.class_weight import compute_class_weight

np.random.seed(42)
tf.random.set_seed(42)
os.environ['PYTHONHASHSEED'] = '42'
os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
tf.config.experimental.enable_op_determinism()

RUN_TAG = "tibok_combined_rr_cnn"
print(f"RUN_TAG = {RUN_TAG}")

gpus = tf.config.list_physical_devices('GPU')
print(f"GPUs available: {len(gpus)}")
for gpu in gpus:
    print(f"  {gpu}")
if not gpus:
    print("No GPU detected — Runtime > Change runtime type > GPU will speed this up substantially.")

"""## Data split — combined MIT-BIH + INCART, patient-level 70/15/15

Streams both databases directly from PhysioNet (no local mirror needed). MIT-BIH contributes
its 44 non-paced records; INCART contributes all 75 recordings. The pooled 119 "patients" are
shuffled once (fixed seed) and split 70/15/15 — train and test therefore each contain a mix of
both databases, so this protocol is **not** directly comparable to the classic de Chazal
DS1/DS2 MIT-BIH-only benchmark table in `TIBOK_RR_CNN.ipynb`; it's the protocol your own
methodology commits to, evaluated on a broader population.
"""

WINDOW_SIZE = 1250
FS = 360

MITDB_RECORDS = [
    '100', '101', '103', '105', '106', '108', '109', '111', '112', '113',
    '114', '115', '116', '117', '118', '119', '121', '122', '123', '124',
    '200', '201', '202', '203', '205', '207', '208', '209', '210', '212',
    '213', '214', '215', '219', '220', '221', '222', '223', '228', '230',
    '231', '232', '233', '234'
]  # MIT-BIH, paced-beat records 102/104/107/217 excluded
INCART_RECORDS = [f"I{i:02d}" for i in range(1, 76)]  # all 75 St. Petersburg INCART recordings

ALL_RECORDS = [('mitdb', r) for r in MITDB_RECORDS] + [('incartdb', r) for r in INCART_RECORDS]

rng_split = np.random.RandomState(42)
shuffled = list(ALL_RECORDS)
rng_split.shuffle(shuffled)
n_total = len(shuffled)
n_train = round(0.70 * n_total)
n_val = round(0.15 * n_total)
TRAIN_RECORDS = shuffled[:n_train]
VAL_RECORDS = shuffled[n_train:n_train + n_val]
TEST_RECORDS = shuffled[n_train + n_val:]

print(f"Total patient-records: {n_total} (MIT-BIH {len(MITDB_RECORDS)} + INCART {len(INCART_RECORDS)})")
print(f"Train ({len(TRAIN_RECORDS)}): {TRAIN_RECORDS}")
print(f"Val   ({len(VAL_RECORDS)}): {VAL_RECORDS}")
print(f"Test  ({len(TEST_RECORDS)}): {TEST_RECORDS}")

LABEL_MAP = {
    'N': 0, 'L': 0, 'R': 0, 'e': 0, 'j': 0,
    'V': 1, 'A': 1, 'F': 1, 'S': 1, 'a': 1, 'J': 1,
}
BEAT_SYMBOLS = set(LABEL_MAP.keys()) | {'B', 'r', 'n', 'E', 'f', 'Q', '/'}

assert not any(r in TRAIN_RECORDS for r in VAL_RECORDS)
assert not any(r in TRAIN_RECORDS for r in TEST_RECORDS)
assert not any(r in VAL_RECORDS for r in TEST_RECORDS)
print("Data split integrity OK.")

"""## Local Drive cache for MIT-BIH + INCART

Both databases are read directly from Google Drive — no download/streaming step.

**Set these to filesystem paths, not sharing links.** Drive is *mounted* at
`/content/drive`, so a folder's path always looks like `/content/drive/MyDrive/<folder>`.
A `https://drive.google.com/drive/folders/...` URL is a browser link and is never a valid
path — and `os.walk()` on one does not raise, it just yields nothing, so the index comes
back empty and the failure surfaces much later and far from its cause.

If a folder was *shared with you* rather than owned by you, it does not appear under
`MyDrive` at all until you add a shortcut: in Drive, right-click the folder → Organise →
**Add shortcut to Drive**. Then use that shortcut's path here.

`resolve_db_source` enforces this: it rejects URLs, searches the mount for the records
when the configured path is wrong, and verifies every required record is present *before*
loading starts.

**If Drive is not usable, it streams from PhysioNet instead** — set `INCART_PREFER` /
`MITDB_PREFER` to `"physionet"` to force that, or leave them `"local"` and the fallback
happens automatically when the folder is missing or incomplete. Both databases are
open-access on PhysioNet and `wfdb` fetches one record at a time, so there is no bulk
download step.

That fallback matters for a *shared* folder. View-only access is enough to read files, and
"Add shortcut to Drive" works at view-only too — but if the owner ticked **"Viewers cannot
download, print, or copy"**, the mount cannot read the bytes at all, and Drive also enforces
per-file download quotas on widely-shared files that a 75-record run can trip partway
through. PhysioNet depends on none of that.
"""

from tibok.data_paths import resolve_db_source, pick_lead

MITDB_PATH = "/content/drive/MyDrive/mit-bih-arrhythmia-database-1.0.0"
INCART_PATH = "/content/drive/MyDrive/incart-arrhythmia-database-1.0.0"  # <-- a PATH, not a sharing URL

# Set either of these to "physionet" to skip Drive entirely for that database and stream
# the records over HTTPS instead. That is the reproducible option: it depends on nothing
# anyone's sharing settings control, and wfdb fetches one record at a time rather than
# mirroring the whole database. Left as "local", a Drive folder is used when it is present
# and complete, and PhysioNet is used automatically when it is not.
MITDB_PREFER = "local"
INCART_PREFER = "local"

DB = {
    "mitdb": resolve_db_source(MITDB_PATH, ["100", "234"], "MIT-BIH", pn_dir="mitdb",
                               required=MITDB_RECORDS, expected_total=48, prefer=MITDB_PREFER),
    "incartdb": resolve_db_source(INCART_PATH, ["I01", "I75"], "INCART", pn_dir="incartdb",
                                  required=INCART_RECORDS, expected_total=75, prefer=INCART_PREFER),
}
for key, src in DB.items():
    print(f"  {key}: {src}")

"""## Loading + RR-interval feature extraction (both databases, read from Drive)

Same RR-interval logic as before, generalized to handle both sources: MIT-BIH loads at its
native 360 Hz directly from `MITDB_PATH`; INCART loads from `INCART_PATH` and is resampled from
257 Hz to 360 Hz (`scipy.signal.resample`), with its annotation sample indices rescaled to
match, so every downstream step (windowing, RR-interval computation in seconds) operates in one
consistent 360 Hz time base regardless of source. INCART's lead II is used as the
MLII-equivalent channel, per the document's stated data-collection plan.
"""

import scipy.signal

# Which lead to pull per database. Selecting by NAME matters: MIT-BIH is mostly ordered
# [MLII, V5], but record 114 is [V5, MLII], so the old `p_signal[:, 0]` fed V5 into the
# model for that one record while every other record contributed MLII. `pick_lead` raises
# rather than guessing when no preferred lead is present.
LEAD_PREFERENCE = {'mitdb': ('MLII', 'II'), 'incartdb': ('II',)}


def load_and_segment(source, record_id, window_size):
    record, annotation = DB[source].read(record_id)
    lead_idx = pick_lead(record, LEAD_PREFERENCE[source], label=source, record_id=record_id)
    signal = record.p_signal[:, lead_idx]
    native_fs = record.fs  # MIT-BIH 360 Hz, INCART 257 Hz

    beat_mask = np.array([s in BEAT_SYMBOLS for s in annotation.symbol])
    beat_samples_native = annotation.sample[beat_mask]
    beat_symbols = np.array(annotation.symbol)[beat_mask]
    if len(beat_samples_native) < 3:
        return [], [], [], []

    if native_fs != FS:
        n_new = int(round(len(signal) * FS / native_fs))
        signal = scipy.signal.resample(signal, n_new)
        beat_samples = np.round(beat_samples_native * (FS / native_fs)).astype(int)
    else:
        beat_samples = beat_samples_native

    half = window_size // 2
    sig_len = len(signal)

    rr = np.diff(beat_samples) / FS
    pre_rr = np.empty(len(beat_samples)); post_rr = np.empty(len(beat_samples))
    pre_rr[0] = rr[0] if len(rr) else 0.8; pre_rr[1:] = rr
    post_rr[-1] = rr[-1] if len(rr) else 0.8; post_rr[:-1] = rr

    local_rr = np.empty(len(beat_samples))
    global_mean_rr = rr.mean() if len(rr) else 0.8
    for i in range(len(beat_samples)):
        window = pre_rr[max(0, i - 10):i]
        local_rr[i] = window.mean() if len(window) > 0 else global_mean_rr
    ratio = pre_rr / (local_rr + 1e-6)

    segments, labels, symbols, rr_feats = [], [], [], []
    for i, (sample, symbol) in enumerate(zip(beat_samples, beat_symbols)):
        if symbol not in LABEL_MAP:
            continue
        if sample - half < 0 or sample + half > sig_len:
            continue
        segments.append(signal[sample - half: sample + half])
        labels.append(LABEL_MAP[symbol])
        symbols.append(symbol)
        rr_feats.append([pre_rr[i], post_rr[i], local_rr[i], ratio[i]])
    return segments, labels, symbols, rr_feats


def build_dataset(record_list):
    all_segments, all_labels, all_symbols, all_rr = [], [], [], []
    for source, rid in record_list:
        segs, labs, syms, rrf = load_and_segment(source, rid, WINDOW_SIZE)
        all_segments.extend(segs); all_labels.extend(labs)
        all_symbols.extend(syms); all_rr.extend(rrf)
        print(f"  {source}/{rid}: {len(segs)} beats loaded")
    return all_segments, all_labels, all_symbols, all_rr


def normalize_batch(segments):
    arr = np.stack(segments).astype(np.float32)
    mean = arr.mean(axis=1, keepdims=True)
    std = arr.std(axis=1, keepdims=True) + 1e-8
    return (arr - mean) / std


print("Loading training records...")
train_segments, train_labels, train_symbols, train_rr = build_dataset(TRAIN_RECORDS)
print("\nLoading validation records...")
val_segments, val_labels, val_symbols, val_rr = build_dataset(VAL_RECORDS)
print("\nLoading held-out test records...")
test_segments, test_labels, test_symbols, test_rr = build_dataset(TEST_RECORDS)
y_test_symbols = np.array(test_symbols)

X_train = normalize_batch(train_segments).reshape(-1, WINDOW_SIZE, 1)
y_train = np.array(train_labels)
RR_train = np.array(train_rr, dtype=np.float32)

X_val = normalize_batch(val_segments).reshape(-1, WINDOW_SIZE, 1)
y_val = np.array(val_labels)
RR_val = np.array(val_rr, dtype=np.float32)

X_test = normalize_batch(test_segments).reshape(-1, WINDOW_SIZE, 1)
y_test = np.array(test_labels)
RR_test = np.array(test_rr, dtype=np.float32)

print(f"\nX_train {X_train.shape}  X_val {X_val.shape}  X_test {X_test.shape}")
print("Train class balance:", pd.Series(y_train).value_counts(normalize=True).to_dict())
print("Test  class balance:", pd.Series(y_test).value_counts(normalize=True).to_dict())

rr_mean = RR_train.mean(axis=0)
rr_std = RR_train.std(axis=0) + 1e-8
RR_train_n = (RR_train - rr_mean) / rr_std
RR_val_n = (RR_val - rr_mean) / rr_std
RR_test_n = (RR_test - rr_mean) / rr_std

"""## Minority-class augmentation — balanced BY SYMBOL, not just positive-vs-negative

Same signal recipe as before (time shift, baseline wander, powerline hum, Gaussian noise,
amplitude scaling), with RR features carried over unchanged for copies since the
augmentation perturbs the waveform and not beat timing.

**What changed: the balancing is now symbol-aware.** Copying every positive beat 2x boosts
V and F by the same factor, so it preserves the imbalance *inside* the positive class
exactly. That class is ~97% V beats, so "balanced" training was in practice training a
V-beat detector, and the pooled sensitivity was a V-beat number wearing an "arrhythmia"
label. One observed test split:

    V  6030 beats -> 0.974 sensitivity
    A   163 beats -> 0.859
    F    23 beats -> 0.087
    S     1 beat  -> 0.000

Sensitivity tracks sample count monotonically. No threshold, loss or quantization setting
fixes that — the model was never shown enough F beats, and the RR features actively mislead
there, since a fusion beat is a sinus and an ectopic beat arriving together and so is not
especially premature.

`BALANCE_STRATEGY` controls it: `"sqrt"` (default) targets counts proportional to sqrt(n),
`"equal"` levels every symbol to the largest, `"none"` reproduces the old uniform 2x
behaviour. `BALANCE_CAP` bounds the multiplier.

**Oversampling cannot create information that is not in the data.** 23 F beats copied 30
times are still 23 F beats, and the model may simply memorise them. If F sensitivity has to
hold up in the write-up, the honest fix is more F beats — or reporting F separately and
saying the study is underpowered for it.
"""

def augment_segment(segment, rng, shift_max=40, noise_std=0.03, scale_range=(0.9, 1.1),
                     baseline_wander_prob=0.3, powerline_prob=0.3):
    seg = segment.copy().astype(np.float32).flatten()
    n = len(seg)
    shift = int(rng.integers(-shift_max, shift_max + 1))
    seg = np.roll(seg, shift)
    if rng.random() < baseline_wander_prob:
        freq = rng.uniform(0.15, 0.4); t = np.arange(n)
        wander_amp = rng.uniform(0.05, 0.15)
        seg = seg + wander_amp * np.sin(2 * np.pi * freq * t / n)
    if rng.random() < powerline_prob:
        freq = rng.choice([50, 60]); t = np.arange(n)
        pl_amp = rng.uniform(0.02, 0.06)
        seg = seg + pl_amp * np.sin(2 * np.pi * freq * t / FS)
    seg = seg + rng.normal(0, noise_std, n).astype(np.float32)
    seg = seg * rng.uniform(*scale_range)
    return seg.reshape(segment.shape)


def augment_dataset(X, rr, y, rng, n_aug_positive=2):
    X_list, rr_list, y_list = [X], [rr], [y]
    idx = np.where(y == 1)[0]
    for _ in range(n_aug_positive):
        X_aug = np.stack([augment_segment(X[i], rng) for i in idx]).astype(np.float32)
        rr_aug = rr[idx]
        y_aug = np.full(len(idx), 1)
        X_list.append(X_aug); rr_list.append(rr_aug); y_list.append(y_aug)
    return np.concatenate(X_list), np.concatenate(rr_list), np.concatenate(y_list)


from tibok.balance import augment_by_symbol, symbol_counts, symbol_sample_weights

BALANCE_STRATEGY = "sqrt"   # "sqrt" | "equal" | "none" (none == the old uniform 2x)
BALANCE_CAP = 10            # ceiling on extra copies per beat

aug_rng = np.random.default_rng(42)
train_symbols_arr = np.array(train_symbols)

print("Positive-class composition BEFORE balancing:", symbol_counts(train_symbols_arr, y_train))
X_train_aug, RR_train_aug, y_train_aug, sym_train_aug = augment_by_symbol(
    X_train, RR_train_n, y_train, train_symbols_arr,
    augment_segment, aug_rng, strategy=BALANCE_STRATEGY, cap=BALANCE_CAP,
)
print("Positive-class composition AFTER  balancing:", symbol_counts(sym_train_aug, y_train_aug))

shuffle_idx = np.random.RandomState(42).permutation(len(y_train_aug))
X_train_aug = X_train_aug[shuffle_idx]; RR_train_aug = RR_train_aug[shuffle_idx]
y_train_aug = y_train_aug[shuffle_idx]; sym_train_aug = sym_train_aug[shuffle_idx]
print(f"After augmentation: X_train {X_train_aug.shape}, binary balance:",
      pd.Series(y_train_aug).value_counts(normalize=True).to_dict())

# Alternative/complementary lever: reweight the loss per beat instead of duplicating data.
# This only works now that focal_loss returns one value per sample -- with the old
# scalar-reducing version, sample_weight was as inert as class_weight was.
USE_SYMBOL_SAMPLE_WEIGHTS = False
sample_weights = (symbol_sample_weights(sym_train_aug, y_train_aug, strategy=BALANCE_STRATEGY)
                  if USE_SYMBOL_SAMPLE_WEIGHTS else None)

"""## Model: CNN branch (morphology) + RR branch (rhythm timing), fused before the classifier head

Uses the same fixed (both-term) focal loss as the baseline notebook, plus a manually boosted
positive-class weight — this is a screening device, so a false negative (missed arrhythmia)
should cost more than a false positive.
"""

def focal_loss(gamma=3.0, alpha=0.3):
    """Focal loss, returning ONE VALUE PER SAMPLE.

    The previous version ended with `tf.reduce_mean(tf.reduce_sum(..., axis=-1))`, which
    collapses the batch axis and hands Keras a scalar. `class_weight` works by scaling each
    sample's loss, so with nothing per-sample left to scale it was almost entirely inert:
    on a 15%-positive problem, a 10x positive weight moved the mean prediction by +0.0036
    with the scalar form against +0.0639 with this one. Every class-weight setting in this
    notebook -- the balanced weights and the 1.3x recall boost on top of them -- was
    therefore doing close to nothing.

    Keeping the batch axis and letting Keras reduce is the fix; the maths is unchanged.
    """
    def focal_loss_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        epsilon = tf.keras.backend.epsilon()
        y_pred = tf.clip_by_value(y_pred, epsilon, 1.0 - epsilon)
        pos_term = -alpha * y_true * tf.pow(1.0 - y_pred, gamma) * tf.math.log(y_pred)
        neg_term = -(1.0 - alpha) * (1.0 - y_true) * tf.pow(y_pred, gamma) * tf.math.log(1.0 - y_pred)
        return tf.reduce_sum(pos_term + neg_term, axis=-1)
    return focal_loss_fixed


def build_model(window_size, n_rr_features=4):
    sig_in = layers.Input(shape=(window_size, 1), name="ecg_window")
    x = sig_in
    for filters, kernel, stride in [(16, 7, 4), (32, 7, 4), (64, 7, 2)]:
        x = layers.Conv1D(filters, kernel_size=kernel, strides=stride, padding='same',
                           kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.Activation('relu')(x)
        x = layers.SpatialDropout1D(0.15)(x)
    x = layers.GlobalAveragePooling1D()(x)

    rr_in = layers.Input(shape=(n_rr_features,), name="rr_features")
    r = layers.Dense(16, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4))(rr_in)

    merged = layers.Concatenate()([x, r])
    merged = layers.Dropout(0.5)(merged)
    merged = layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4))(merged)
    merged = layers.Dropout(0.4)(merged)
    out = layers.Dense(1, activation='sigmoid')(merged)

    model = Model(inputs=[sig_in, rr_in], outputs=out)
    model.compile(
        optimizer=Adam(learning_rate=3e-4),
        loss=focal_loss(gamma=3.0, alpha=0.3),
        metrics=['accuracy', tf.keras.metrics.Precision(name='precision'),
                 tf.keras.metrics.Recall(name='recall')]
    )
    return model


build_model(WINDOW_SIZE).summary()

"""## Training — best-of-N candidate search, model selected by validation PR-AUC

On Colab with a GPU this trains in a couple of minutes; raise `N_CANDIDATES` (e.g. to 8, as in
the baseline notebook) for a more thorough search once you've confirmed the pipeline runs
end-to-end.
"""

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6)

class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train_aug), y=y_train_aug)
class_weight_dict = {i: w for i, w in enumerate(class_weights)}
class_weight_dict[1] *= 1.3  # extra recall bias — a missed arrhythmia is costlier than a false alarm
print(f"Class weights: {class_weight_dict}")

N_CANDIDATES = 3
EPOCHS = 50
BATCH_SIZE = 128

best_val_pr_auc = -1
best_model = None
all_candidates, candidate_val_pr_aucs = [], []

t0 = time.time()
for i in range(N_CANDIDATES):
    print(f"\n=== Candidate {i+1}/{N_CANDIDATES} ===")
    tf.keras.utils.set_random_seed(4000 + i)
    candidate = build_model(WINDOW_SIZE)
    candidate.fit(
        [X_train_aug, RR_train_aug], y_train_aug,
        validation_data=([X_val, RR_val_n], y_val),
        epochs=EPOCHS, batch_size=BATCH_SIZE,
        callbacks=[early_stop, reduce_lr],
        class_weight=class_weight_dict, sample_weight=sample_weights, verbose=2,
    )
    val_probs = candidate.predict([X_val, RR_val_n], batch_size=256, verbose=0).flatten()
    val_pr_auc = average_precision_score(y_val, val_probs)
    print(f"Candidate {i+1} val PR-AUC: {val_pr_auc:.4f}")
    all_candidates.append(candidate)
    candidate_val_pr_aucs.append(val_pr_auc)
    if val_pr_auc > best_val_pr_auc:
        best_val_pr_auc = val_pr_auc
        best_model = candidate

print(f"\nTraining wall time: {(time.time()-t0)/60:.1f} min")
print(f"Best candidate val PR-AUC: {best_val_pr_auc:.4f}  (per-candidate: {candidate_val_pr_aucs})")
model = best_model
model.save(f'{RUN_TAG}_model.keras')

"""## Threshold selection on validation, evaluation on the held-out DS2 test set

Reports three operating points, same as the baseline notebook: F1-optimal, Youden's-J
(balanced sensitivity/specificity), and a high-sensitivity point targeting ≥90% recall. Given
TIBOK is a *screening* device — the hypotheses explicitly treat a missed arrhythmia as
costlier than a false alarm — the Youden or high-sensitivity threshold is the more defensible
deployment choice, not F1-optimal.
"""

y_val_probs = model.predict([X_val, RR_val_n], batch_size=256, verbose=0).flatten()
precisions_val, recalls_val, thresholds_val = precision_recall_curve(y_val, y_val_probs)
f1_scores_val = 2 * (precisions_val * recalls_val) / (precisions_val + recalls_val + 1e-8)
f1_optimal_threshold = thresholds_val[np.argmax(f1_scores_val[:-1])]

specs, sens = [], []
for t in thresholds_val:
    preds = (y_val_probs > t).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_val, preds).ravel()
    specs.append(tn / (tn + fp) if (tn + fp) > 0 else 0)
    sens.append(tp / (tp + fn) if (tp + fn) > 0 else 0)
specs, sens = np.array(specs), np.array(sens)
youden_threshold = thresholds_val[np.argmax(sens + specs - 1)]

TARGET_SENSITIVITY = 0.90
valid_mask = sens >= TARGET_SENSITIVITY
if valid_mask.any():
    valid_specs = np.where(valid_mask, specs, -1)
    high_sens_threshold = thresholds_val[np.argmax(valid_specs)]
else:
    high_sens_threshold = thresholds_val[np.argmax(sens)]

# Precision-floor threshold: the lowest threshold on VALIDATION that still reaches
# >=90% precision there (picking the lowest such threshold keeps recall as high as
# possible while satisfying the floor). Chosen on val, only ever evaluated on test —
# same no-leakage protocol as the other three thresholds. This has empirically been
# the best-performing operating point (higher precision AND higher F1 than F1-optimal,
# for only a small recall cost) on both models trained so far, so it's the deploy
# recommendation below — but re-check it after every retrain, since the "best"
# threshold depends on that run's specific precision-recall curve.
PRECISION_FLOOR_TARGET = 0.90
valid_prec_idx = np.where(precisions_val[:-1] >= PRECISION_FLOOR_TARGET)[0]
if len(valid_prec_idx) > 0:
    precision_floor_90_threshold = thresholds_val[valid_prec_idx[0]]
else:
    precision_floor_90_threshold = thresholds_val[np.argmax(precisions_val[:-1])]

print(f"F1-optimal threshold (val): {f1_optimal_threshold:.4f}")
print(f"Youden's-J threshold (val): {youden_threshold:.4f}")
print(f"High-sensitivity threshold (val, target>=90%): {high_sens_threshold:.4f}")
print(f"Precision-floor threshold (val, target>=90% precision): {precision_floor_90_threshold:.4f}")


def evaluate(y_true, probs, threshold, label):
    pred = (probs > threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, pred).ravel()
    metrics = dict(
        threshold=float(threshold), accuracy=accuracy_score(y_true, pred),
        precision=precision_score(y_true, pred, zero_division=0),
        sensitivity=recall_score(y_true, pred, zero_division=0),
        specificity=tn / (tn + fp) if (tn + fp) > 0 else 0,
        f1_score=f1_score(y_true, pred, zero_division=0),
        roc_auc=roc_auc_score(y_true, probs), pr_auc=average_precision_score(y_true, probs),
        tp=int(tp), fp=int(fp), tn=int(tn), fn=int(fn),
    )
    print(f"\n--- {label} (threshold={threshold:.4f}) ---")
    for k, v in metrics.items():
        print(f"  {k}: {v}")
    return metrics


y_test_probs = model.predict([X_test, RR_test_n], batch_size=256, verbose=0).flatten()

results = {
    "f1_optimal": evaluate(y_test, y_test_probs, f1_optimal_threshold, "TEST — F1-optimal"),
    "youden": evaluate(y_test, y_test_probs, youden_threshold, "TEST — Youden-balanced"),
    "high_sensitivity": evaluate(y_test, y_test_probs, high_sens_threshold, "TEST — High-sensitivity (>=90% target)"),
    "precision_floor_90": evaluate(y_test, y_test_probs, precision_floor_90_threshold, "TEST — Precision-floor (>=90% val precision) [recommended deploy threshold]"),
}

"""## Per-AAMI-symbol sensitivity breakdown

The pooled "arrhythmia" sensitivity can hide a real weakness — if the model is strong on
common V-beats but weak on rarer F or J beats, the pooled number still looks fine because
V-beats dominate the positive class.
"""

y_test_pred = (y_test_probs > precision_floor_90_threshold).astype(int)
symbol_breakdown = {}
for sym in sorted(set(y_test_symbols[y_test == 1])):
    mask = (y_test_symbols == sym) & (y_test == 1)
    n = int(mask.sum())
    if n == 0:
        continue
    caught = int((y_test_pred[mask] == 1).sum())
    symbol_breakdown[sym] = {"n": n, "caught": caught, "sensitivity": caught / n}

print("Per-AAMI-symbol sensitivity (precision-floor threshold):")
for sym, d in symbol_breakdown.items():
    print(f"  {sym}: {d['caught']}/{d['n']} ({d['sensitivity']:.4f})")

"""## INT8 post-training quantization — the model that actually ships on the nRF52840

Calibrates on the validation set (never the test set), converts both inputs to INT8, and
re-evaluates on the same held-out test set to answer RQ2.1/RQ2.3 (does quantization change
F1 / specificity?).

**The `input->dims->size != 4 (3 != 4)` failure is fixed, and it was not what the earlier note
in this notebook said it was.** It is neither environment-specific nor weight-dependent — a
freshly-initialized model fails identically once you actually run the calibration pass. The
cause is that `TFLiteConverter` does not preserve `model.inputs` ordering for a multi-input
model: on TF 2.21 it emits the graph inputs as `[rr_features, ecg_window]` while Keras lists
them as `[ecg_window, rr_features]`. The old `representative_dataset` yielded
`[X_val_sample, RR_val_sample]` positionally, so the 4-element RR vector was fed into the
Conv1D branch — rank 3 where the kernel wants rank 4 — hence `3 != 4` at CONV_2D node 1.

The `tibok.quantization` module (written to disk by the cell above) fixes this by probing the converter's actual input order first (one
throwaway float conversion) and then feeding calibration samples in *that* order. It also no
longer silently falls back to dynamic-range quantization: TFLite-Micro has no dynamic-range
kernels for this graph, so that fallback produced a model that loads on desktop but fails at
`AllocateTensors()` on the nRF52840 — a conversion bug quietly converted into a firmware bug.
"""

import sys

# In the generated Colab notebook the cell above this one is a `%%writefile` cell that
# drops `tibok/quantization.py` straight onto the runtime's disk, so the notebook is
# self-contained: no clone, no upload, no GitHub auth. That matters because this repo is
# private -- `git clone` from a Colab runtime would prompt for credentials and fail.
#
# Running this file as a plain script instead (outside Colab) just imports the module
# from the repo checkout it already sits in.
if "." not in sys.path:
    sys.path.insert(0, ".")
from tibok.quantization import quantize_and_test

THRESHOLDS = {
    "f1_optimal": float(f1_optimal_threshold),
    "youden": float(youden_threshold),
    "high_sensitivity": float(high_sens_threshold),
    "precision_floor_90": float(precision_floor_90_threshold),
}

quant_report = quantize_and_test(
    model=model,
    X_val=X_val, RR_val_n=RR_val_n,
    X_test=X_test, RR_test_n=RR_test_n, y_test=y_test,
    y_val=y_val,   # enables STEP 4b: thresholds recalibrated on INT8 validation scores
    thresholds=THRESHOLDS,
    window_size=WINDOW_SIZE,
    run_tag=RUN_TAG,
    test_symbols=y_test_symbols,
    deploy_threshold_name="precision_floor_90",
    rr_mean=rr_mean, rr_std=rr_std,
    n_calib=800,
    n_boot=2000,
    batch_one=True,   # mirrors how the firmware invokes the model, one window at a time
    out_dir=".",
)

"""## Optional: precision/sensitivity sweep over the loss and class-weight knobs

The model is over on sensitivity (0.965 against a 0.95 target) and under on precision
(0.852 against 0.90), so the settings biasing it toward recall are being paid for in the
wrong currency. This sweeps them.

Two knobs:

- `alpha` — the focal-loss weight on the positive term. Lower favours precision, higher
  favours recall. Currently 0.3.
- `pos_boost` — the manual multiplier on top of balanced class weights. Currently 1.3.
  **Setting it to 1.0 removes the recall bias entirely**, which is the cleanest precision
  lever available.

`pos_boost` only started doing anything once `focal_loss` was fixed to return one value per
sample — see its docstring. Before that fix every class-weight setting here was inert, so
any earlier tuning of these numbers told you nothing.

**The sweep never touches the test set.** Validation is split in two: one half chooses the
operating point, the other scores the configuration. Ranking on the same beats used to pick
the threshold would flatter every configuration and flatter the overfitted ones most.
Only `finalize_on_test` reads test data, once, after the winner is settled. If you re-run
the sweep after seeing test numbers, the test set has become a second validation set and
the write-up should say so.

Cost is one training run per (config, seed): the default 6-config grid at one seed is about
six runs. Seed noise here is large, so `n_seeds=2` ranks more reliably at double the cost.
Results checkpoint after every run; `resume=True` continues an interrupted session.
"""

RUN_SWEEP = False   # flip to True to run the sweep
SWEEP_SEEDS = 1

if RUN_SWEEP:
    from tibok.sweep import make_grid, run_sweep, summarize_sweep, print_sweep

    def sweep_train_one(cfg, seed):
        tf.keras.utils.set_random_seed(seed)
        m = build_model(WINDOW_SIZE)
        m.compile(
            optimizer=Adam(learning_rate=3e-4),
            loss=focal_loss(gamma=cfg["gamma"], alpha=cfg["alpha"]),
            metrics=['accuracy', tf.keras.metrics.Precision(name='precision'),
                     tf.keras.metrics.Recall(name='recall')],
        )
        cw = compute_class_weight(class_weight='balanced',
                                  classes=np.unique(y_train_aug), y=y_train_aug)
        d = {i: w for i, w in enumerate(cw)}
        d[1] *= cfg["pos_boost"]
        m.fit([X_train_aug, RR_train_aug], y_train_aug,
              validation_data=([X_val, RR_val_n], y_val),
              epochs=EPOCHS, batch_size=BATCH_SIZE,
              callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=6,
                                                          restore_best_weights=True),
                         tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                                              patience=3, min_lr=1e-6)],
              class_weight=d, verbose=0)
        return m

    sweep_grid = make_grid(pos_boosts=(1.0, 1.3), alphas=(0.15, 0.30, 0.45))
    sweep_rows = run_sweep(sweep_train_one, sweep_grid, X_val, RR_val_n, y_val,
                           window_size=WINDOW_SIZE, n_seeds=SWEEP_SEEDS,
                           out_dir=".", run_tag=RUN_TAG, resume=True)
    sweep_summary = summarize_sweep(sweep_rows)
    print_sweep(sweep_summary)
else:
    sweep_summary = None
    print("RUN_SWEEP is False -- skipping the loss/class-weight sweep.")

"""## Optional: R independent trials, for a variance-aware answer to RQ2.1/RQ2.3

Everything above is **one** model, so it supports "quantization cost F1 0.040 *in this
run*" and nothing stronger. This section repeats the whole train -> quantize -> evaluate
experiment `N_TRIALS` times with different seeds and reports mean +/- SD, so the claim
becomes "F1 0.040 +/- <sd> across N runs".

**This is not the same as raising `N_CANDIDATES`.** That is a best-of-N *search*: it trains
N models, keeps the best on validation PR-AUC, and discards the rest. Raising it gives one
model chosen from a bigger pool, and makes the winner's validation PR-AUC *more*
optimistically biased, since you report the maximum of N noisy draws from the same set you
selected on. It adds no evidence about reproducibility. A trial is an independent
replication and does.

The patient split is held fixed across trials on purpose -- it is the split the methodology
commits to, and re-drawing it per trial would change the study population. So what is
measured here is **training variance** (initialization, augmentation draws, shuffling), not
variance across patient populations. State which one you are reporting.

Cost: roughly one training run per trial. At ~8 min/run, `N_TRIALS = 10` is about 80
minutes. Results are checkpointed to `<RUN_TAG>_trials.json` after every trial and
`resume=True` picks up where a disconnected runtime stopped, so this survives Colab
dropping the session partway.
"""

RUN_TRIALS = False   # flip to True to run the replication study
N_TRIALS = 10
CANDIDATES_PER_TRIAL = 1  # >1 keeps best-of-N inside each trial; cost multiplies

if RUN_TRIALS:
    from tibok.trials import run_trials, summarize_trials, print_trial_summary

    def trial_build(seed):
        tf.keras.utils.set_random_seed(seed)
        return build_model(WINDOW_SIZE)

    def trial_fit(model, seed):
        model.fit(
            [X_train_aug, RR_train_aug], y_train_aug,
            validation_data=([X_val, RR_val_n], y_val),
            epochs=EPOCHS, batch_size=BATCH_SIZE,
            callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=6,
                                                        restore_best_weights=True),
                       tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                                            patience=3, min_lr=1e-6)],
            class_weight=class_weight_dict, verbose=0,
        )

    trial_rows = run_trials(
        trial_build, trial_fit,
        X_train_aug, RR_train_aug, y_train_aug,
        X_val, RR_val_n, y_val,
        X_test, RR_test_n, y_test,
        window_size=WINDOW_SIZE, n_trials=N_TRIALS,
        candidates_per_trial=CANDIDATES_PER_TRIAL,
        out_dir=".", run_tag=RUN_TAG, resume=True,
    )
    trial_summary = summarize_trials(trial_rows)
    print_trial_summary(trial_summary)
else:
    trial_summary = None
    print("RUN_TRIALS is False -- skipping the replication study.")

"""## Results CSV — every candidate, FP32 and INT8, plus mean/SD

Writes `<RUN_TAG>_results_summary.csv` with the fixed column layout:

    Model,Threshold Type,Threshold Value,Accuracy,Sensitivity,Specificity,Precision,F1,ROC-AUC,PR-AUC

**All candidates appear, not just the selected one.** On one observed run the eight
candidates scored 0.8865 / 0.7418 / 0.7516 / 0.7305 / 0.7352 / 0.6813 / 0.6938 / 0.7420 on
validation PR-AUC: the winner sat six standard deviations above the other seven, which
cluster at 0.725 +/- 0.027. A table showing only the winner presents a lucky draw as the
model's performance. With all eight plus mean and SD rows, a reader can see how much of the
headline is selection.

Every row uses the **same** thresholds — the ones chosen on validation from the selected
model. Per-candidate thresholds would make each row internally optimal but mutually
incomparable, which defeats the purpose of one table.

**Selection remains on validation.** These are test metrics for every candidate, shown for
transparency, and that is only honest while the deployed model stays the validation winner
— marked `[Selected]` in the Model column. Choosing a different row because it scores
better on test turns the test set into a second validation set and the headline number
stops estimating held-out performance.
"""

from tibok.report import build_results_table, write_results_csv

WRITE_RESULTS_CSV = True
CSV_QUANTIZE_EVERY_CANDIDATE = True   # False = FP32 rows only (skips 8 INT8 conversions)

if WRITE_RESULTS_CSV:
    selected_index = int(np.argmax(candidate_val_pr_aucs))
    print(f"Selected candidate: C{selected_index + 1} "
          f"(val PR-AUC {candidate_val_pr_aucs[selected_index]:.4f})")
    print(f"Candidate val PR-AUCs: {[round(float(v), 4) for v in candidate_val_pr_aucs]}")

    results_rows = build_results_table(
        all_candidates, candidate_val_pr_aucs, selected_index, THRESHOLDS,
        X_test, RR_test_n, y_test, X_val, RR_val_n, WINDOW_SIZE,
        quantize=CSV_QUANTIZE_EVERY_CANDIDATE, n_calib=800, batch_one=False,
    )
    write_results_csv(f"{RUN_TAG}_results_summary.csv", results_rows)

    # Echo the summary block so the numbers are visible without opening the file.
    print()
    print(f"{'Model':<22}{'Threshold Type':<18}{'Sens':>8}{'Spec':>8}{'Prec':>8}{'F1':>8}")
    for r in results_rows:
        if "mean" in str(r["Model"]) or "SD" in str(r["Model"]):
            print(f"{r['Model']:<22}{r['Threshold Type']:<18}"
                  f"{r['Sensitivity']:>8}{r['Specificity']:>8}"
                  f"{r['Precision']:>8}{r['F1']:>8}")
else:
    print("WRITE_RESULTS_CSV is False -- skipping the results CSV.")

"""## Save + download everything

`quantize_and_test` has already written `<RUN_TAG>_model_int8.tflite`, `<RUN_TAG>_model_int8.h`
and `<RUN_TAG>_quantization_report.json`. The training summary below is merged with the
quantization report so one JSON carries the whole run.
"""

summary = {
    "candidate_val_pr_aucs": [float(v) for v in candidate_val_pr_aucs],
    "best_val_pr_auc": float(best_val_pr_auc),
    "thresholds": THRESHOLDS,
    "deploy_threshold_recommended": "precision_floor_90",
    "test_results": results,
    "symbol_breakdown": symbol_breakdown,
    "rr_feature_norm": {"mean": rr_mean.tolist(), "std": rr_std.tolist()},
    "quantization": quant_report,
    "trials": trial_summary,
    "sweep": sweep_summary,
}
with open(f'{RUN_TAG}_summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

from google.colab import files
for fname in [f'{RUN_TAG}_model_int8.h', f'{RUN_TAG}_model_int8.tflite',
              f'{RUN_TAG}_quantization_report.json', f'{RUN_TAG}_summary.json',
              f'{RUN_TAG}_results_summary.csv']:
    if os.path.exists(fname):
        files.download(fname)
